### ISSUE TITLE
performance?

### ISSUE THREAD

**Issue by androidfanboi** [filipdanic/spicy-datatable#1]
i see the table works good with 1000 rows; how does it perform with 10k or 100k rows? can you add a live example or something? tnx!

**Comment by filipdanic** [comment]
Good question, thank you for your interest! I will work on library this week and try to address this issue.

**Comment by filipdanic** [comment]
So, I  got around to doing some testing. Generally, the navigation and rendering of the content works pretty fast for 1,000,000+ rows. However, the search feature starts to suffer and block the interface at around 100k or so. Adding a debounce while the user is still typing is a step in the right direction, but we will probably have to make the search async. I’ll open a separate issue for this.
