### ISSUE TITLE
Upgrade to React 16

### ISSUE THREAD

**Issue by filipdanic** [filipdanic/spicy-datatable#12]
I plan on doing this, but if anyone wants to take it over that would be great.

Honestly, just bump the version to React16 and verify that everything works well. There should be no issues with compatibility. We already use `prop-types` so no migration needed there.

**Comment by schmalzs** [comment]
Hey @filipdanic - I'm happy to tackle this one.

**Comment by filipdanic** [comment]
Hey, @scott-schmalz!

Thank you for taking the time and opening a pull request. I will review it this week and merge it as soon as possible.

**Comment by filipdanic** [comment]
Thank you for your contribution @scott-schmalz, it will be very important as we move toward the `1.0.0` release. I added you to the contributor list in the README. 

Cheers!
