### ISSUE TITLE
Fix "Failed prop type: React.PropTypes type checking code is stripped in production."

### ISSUE THREAD

**Issue by sadi304** [filipdanic/spicy-datatable#15]
## Expected Behavior
 No error in prop types

## Actual Behavior
 Warning "Failed prop type: React.PropTypes type checking code is stripped in production."

This maybe an issue with the version 

## Specifications

"react": "^16.2.0",
"spicy-datatable": "^0.5.0",

**Comment by filipdanic** [comment]
Hey Sadi, thanks for reporting. I might have a look at it tomorrow or on Monday. If you find the issue and know how to solve it, feel free to submit a PR.

**Comment by filipdanic** [comment]
The issue was that the `PropTypes` object was not being excluded from the build via webpack. I’ve fixed the issue and there is a new version of the module (`0.6.0`) available which fixes this error.

Thanks for reporting @sadi304! 👍
