### ISSUE TITLE
Having issue with searching table inside div/span

### ISSUE THREAD

**Issue by MahbbRah** [filipdanic/spicy-datatable#16]
I'm having issues with searching the table when I wrap my data with a **span/div** . I need those wrapper so how I can teach Spicy table to check searc data inside the wrapper field? Please give me a solid solution for this.

Check below I've attached my attempt

Regards
Mahbub

![image](https://user-images.githubusercontent.com/10045253/38286504-88cfbc5a-37e7-11e8-9ea8-15846eb88da8.png)

![image](https://user-images.githubusercontent.com/10045253/38286519-a42a7012-37e7-11e8-9af9-b336f7371b60.png)

**Comment by MahbbRah** [comment]
Hell Yeah! 

By leveraging React 16 return as an array the problem has resolved!! 

Check Below :1st_place_medal: 
![image](https://user-images.githubusercontent.com/10045253/38287108-c14119dc-37ea-11e8-9641-d8b9f397596f.png)

**Comment by filipdanic** [comment]
Hey, @MahbbRah!

Another thing you might be interested in is the `customFilter` prop. Here’s an example: https://github.com/filipdanic/spicy-datatable#custom-filter

But if your solution works for you then that’s awesome! :)

**Comment by PIlepRusel** [comment]
How can i wrap the data into span/div ?

**Comment by filipdanic** [comment]
Here’s an example I made with CodeSandbox: https://codesandbox.io/s/ov4po21nky

The short version is: you can remap your data into React components or elements and get it inserted into the table.
