### ISSUE TITLE
Need Sorting for column

### ISSUE THREAD

**Issue by shahidulkareem** [filipdanic/spicy-datatable#17]
## Expected Behavior
We need sorting feature for our project.

## Actual Behavior
Currently, there is no sorting feature included.

**Comment by filipdanic** [comment]
Thanks for opening an issue!

Column sorting has been requested before (e.g. #14), so it makes sense to add it in. I can’t work on it in the near future, but would be happy to review a PR!

To get started, you could see to it that `DatatableHeader` implement an `onClick` handler to call a column sorting function. You could place the sorting function itself inside of `SpicyDatatable.js` and keep track of which columns are selected for sorting via the local state.

**Comment by shahidulkareem** [comment]
Thanks for your kind reply.
I have implemented sorting functionality for this project. please have a look.I have tested it's working fine[.zip file included] 
[spicy-datatable-master.zip](https://github.com/filipdanic/spicy-datatable/files/2610829/spicy-datatable-master.zip)

**Comment by filipdanic** [comment]
Hey, glad to hear you have something going! 😄 But I can’t review/merge this unless it’s a pull request. You’ll have to fork this repo, make your changes, and then submit a PR. If this is new to you, there’s a [tutorial here that you can check out.](https://guides.github.com/activities/forking/)

**Comment by shahidulkareem** [comment]
Thank you. Now, I have submitted PR for sorting.please have a look.

**Comment by shahidulkareem** [comment]
Hi, I have done your requested changes.please have a look.

**Comment by shahidulkareem** [comment]
Hi, have you checked my changes in submitted PR. please have a look and let me know the status. Thank you.

**Comment by filipdanic** [comment]
Thanks for submitting your changes. I’ll try to have a look at it today and maybe do a merge.

**Comment by filipdanic** [comment]
I’ve merged your changes and made some minor changes. The new sorting functionality is available from version `0.8.0`. :) Thank you for your contribution!
