### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by shahidulkareem** [filipdanic/spicy-datatable#18]
While deployment i have seen below error. Can you able to figure out below code.

Error in   TypeError: Cannot read property '0' of undefined
  
  - ExternalModuleFactoryPlugin.js:19 
    [spicy-datatable-master]/[webpack]/lib/ExternalModuleFactoryPlugin.js:19:40
  
  - NormalModuleFactory.js:159 
    [spicy-datatable-master]/[react-scripts]/[webpack]/lib/NormalModuleFactory.j    s:159:3
  
  - Tapable.js:75 NormalModuleFactory.applyPluginsAsyncWaterfall
    [spicy-datatable-master]/[tapable]/lib/Tapable.js:75:69
  
  - NormalModuleFactory.js:144 NormalModuleFactory.create
    [spicy-datatable-master]/[react-scripts]/[webpack]/lib/NormalModuleFactory.j    s:144:8
  
  - Compilation.js:356 Compilation.process [as _addModuleChain]
    [spicy-datatable-master]/[react-scripts]/[webpack]/lib/Compilation.js:356:16  
  - Compilation.js:424 Compilation.process [as addEntry]
    [spicy-datatable-master]/[react-scripts]/[webpack]/lib/Compilation.js:424:7
  
  - SingleEntryPlugin.js:24 Compiler.<anonymous>
    [spicy-datatable-master]/[webpack]/lib/SingleEntryPlugin.js:24:16
  
  - Tapable.js:107 Compiler.applyPluginsParallel
    [spicy-datatable-master]/[tapable]/lib/Tapable.js:107:14
  
  - Compiler.js:394 Compiler.compile
    [spicy-datatable-master]/[react-scripts]/[webpack]/lib/Compiler.js:394:7
  
  - Compiler.js:203 Compiler.runAsChild
    [spicy-datatable-master]/[react-scripts]/[webpack]/lib/Compiler.js:203:7
  
  - compiler.js:70 
    [spicy-datatable-master]/[html-webpack-plugin]/lib/compiler.js:70:19
  
  - compiler.js:69 Object.compileTemplate
    [spicy-datatable-master]/[html-webpack-plugin]/lib/compiler.js:69:10
  
  - index.js:47 Compiler.<anonymous>
    [spicy-datatable-master]/[html-webpack-plugin]/index.js:47:40
![screenshot from 2018-11-22 20-25-08](https://user-images.githubusercontent.com/38592973/48909935-a542f780-ee94-11e8-81eb-b742f8457658.png)

**Comment by filipdanic** [comment]
Hello 👋

If you can identify the reason behind the error that you’re getting and narrow it down, I might be able to help. Otherwise, this isn’t really something I can help with. Sorry! :(

**Comment by shahidulkareem** [comment]
Thank you for your reply. 
After adding below dependencies issue has been fixed.
"react-scripts": "^0.8.4",
"tapable": "^1.1.0",
"html-webpack-plugin": "^3.2.0"

**Comment by filipdanic** [comment]
Awesome, good to hear!
