### ISSUE TITLE
Sort By Date functionality not working

### ISSUE THREAD

**Issue by shahidulkareem** [filipdanic/spicy-datatable#22]
I noticed sort is not working for date column. It is fixed now. I have submitted PR. Please have a look

**Comment by shahidulkareem** [comment]
I have submitted PR again. Please have a look

**Comment by shahidulkareem** [comment]
Have you checked submitted PR. Please have a look

**Comment by filipdanic** [comment]
New version, `0.8.2` is live and it contains the PR you submitted @shahidulkareem! 🎉
