### ISSUE TITLE
[feature request] custom filter function option

### ISSUE THREAD

**Issue by octodroidrus** [filipdanic/spicy-datatable#3]
hi,

can you add an option for a custom filter function? we could just provide it via the configuration prop

e.g. our own: filterRows(rows, columns, searchQuery = '') {}

?

**Comment by filipdanic** [comment]
I can add this when I get a chance.

But, if anyone else is up for it, let me know. Very easy feature.

**Comment by sahiljain112** [comment]
I can help out with that. But by custom filter function, did you mean 'filter by name', 'filter by email' or something else?

**Comment by filipdanic** [comment]
@sahiljain112 thanks for commenting and taking an interest!

So this was the idea I believe:

in `src/spicy-datatable/SpicyDatatable.js` on line 152 there is this:

`const filteredRows = value.length === 0 ? [] : filterRows(rows, columns, value);`

`filterRows` is a function that goes through all the `columns` of every `row` and looks for the `value` (entered by the user in the search bar). 

What @octodroidrus is proposing is to provide an ability for users to pass in their own filter function via the `config` prop that accepts these arguments and returns a list of rows. This way users can define their own filtering logic.

If you’d like to take this one I‘ll gladly assign it you!

**Comment by sahiljain112** [comment]
Alright. You can assign it to me.

**Comment by filipdanic** [comment]
yeah, you beat me to it :) great stuff!

**Comment by filipdanic** [comment]
Updated the readme with the new prop, also added you as a contributor, hoping this will encourage more people to join! I will close this then. 🙌

**Comment by octodroidrus** [comment]
yes, this was what i had in mind @filipdanic, @sahiljain112 

btw, npm says latest version is 0.1.15, but when i did a npm install of 0.1.17 it worked and i got the new code. npm seems to be bugged.
