### ISSUE TITLE
[feature request] download as .csv

### ISSUE THREAD

**Issue by filipdanic** [filipdanic/spicy-datatable#6]
Add an optional `Download as .csv` button to table that downloads all the currently visible rows.

We can use something like https://github.com/filipdanic/json2csvexporter

You just need to pass down the columns as the rows as arguments and lib will do the rest.

**Up for grabs and beginner friendly!**

**Comment by octodroidrus** [comment]
csv is cool, but excel would be amazing

is it a hard format to print in?

**Comment by filipdanic** [comment]
no idea about the excel thing, and it seems a bit too far down the road right now :|

**Comment by joeyspaaa2** [comment]
.csv and .xls would be cool features, useful for building bussines-y products with React

**Comment by lex111** [comment]
I'll take it.

**Comment by filipdanic** [comment]
Hey, @lex111 awesome to hear that!

Let me know how it’s going. We just upgraded the master branch to use React16 so it’s useful that you rebase on top of that. The library already has CSV download support, so I suppose you want to add XLS support? How do you plan on implementing that?

**Comment by lex111** [comment]
@filipdanic oops, I did not notice that there is already support for CSV download. Probably it will be difficult to implement XLS support, what recommendations do you have in this regard?

**Comment by filipdanic** [comment]
@lex111 honestly not too sure. The problem here is that we will have to likely introduce a new dependency. That’s not a big deal if the bundle won’t increase too much, but most libraries that handle this seem to be rather big.

Maybe `js-xlsx` could work? Here’s their demo for React https://github.com/SheetJS/js-xlsx/tree/master/demos/react

**Comment by filipdanic** [comment]
The `.xlsx` feature might be too ambitious for now, so I’ll close this issue.
