### ISSUE TITLE
[idea] revamp search/filter with `js-search`

### ISSUE THREAD

**Issue by filipdanic** [filipdanic/spicy-datatable#7]
Just saw this – https://github.com/bvaughn/js-search – and it looks pretty good. We could simply wrap around it and use it instead. Seems like it is a more reliable solution.

The only issue I see is that it’s another dependency. It will add another 8.45 KB to the production bundle.

**Comment by joeyspaaa2** [comment]
imho no need for extra dependency, if people want it they can pass it in via the custom search prop

**Comment by filipdanic** [comment]
Yes, I think so too. The ability to pass a search function via `customFilter` with the signature `(rows, columns, searchQuery) => resultRows` seems like a good enough solution for everyone who isn’t happy with the current search.
